services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: for-little-be
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    networks:
      - nginx_network
    restart: unless-stopped

networks:
  nginx_network:
    external: true
